AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DeployId:
    Type: String
    Default: afsf34sfdg
  SourceCodeBucket:
    Type: String
    Default: afsf34sfdg
Resources:
  CounterDB:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: CounterDB
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - KeyType: HASH
          AttributeName: id
  RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      EndpointConfiguration:
        Types:
          - REGIONAL
      Body:
        openapi: "3.0.1"
        info:
          title: "EducativeRestAPI"
          description: "Rest API for Educative API Gateway Course"
          version: "2022-06-06T10:08:49Z"
        paths:
          /:
            get:
              responses:
                "200":
                  description: "200 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Empty"
              x-amazon-apigateway-integration:
                credentials: !Sub "arn:aws:iam::${AWS::AccountId}:role/EducativeRole"
                httpMethod: "POST"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:dynamodb:action/UpdateItem"
                responses:
                  default:
                    statusCode: "200"
                    responseTemplates:
                      application/json: "#set($value = $input.json('Attributes.counterValue.N'))\r\n#set($l = $value.length())\r\n#set($l = $l - 1)\r\n$value.substring(1,$l)"
                requestTemplates:
                  application/json: '{"TableName": "CounterDB","Key": {"id": {"S": "id"}},"UpdateExpression": "set counterValue = counterValue + :num","ExpressionAttributeValues": {":num": {"N": "1"}},"ReturnValues" : "UPDATED_OLD"}'
                passthroughBehavior: "when_no_templates"
                type: "aws"
            put:
              responses:
                "200":
                  description: "200 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Empty"
              x-amazon-apigateway-integration:
                credentials: !Sub "arn:aws:iam::${AWS::AccountId}:role/EducativeRole"
                httpMethod: "POST"
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:dynamodb:action/PutItem"
                responses:
                  default:
                    statusCode: "200"
                requestTemplates:
                  application/json: '{"TableName": "CounterDB","Item": {"id": {"S": "id"}, "counterValue": {"N": "1"}}}'
                passthroughBehavior: "when_no_templates"
                type: "aws"
        components:
          schemas:
            Empty:
              title: "Empty Schema"
              type: "object"
      Name: EducativeRestAPI
      Description: "Rest API for Educative API Gateway Course"
      Mode: overwrite
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EducativeRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
        - PolicyName: dynamo
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt CounterDB.Arn
  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: RestAPI
      StageName: v1
